/**
 * Robotics Resources - Tinkerers Lab Dataset
 * Extracted and enriched from Readme.md
 */

const CATEGORIES = [
  { id: "all", name: "All Domains", icon: "cpu", count: 36 },
  { id: "ros2", name: "ROS2", icon: "layers", count: 8, badge: "Industry Standard: Humble" },
  { id: "control-systems", name: "Control Systems", icon: "activity", count: 3 },
  { id: "nav2-moveit2", name: "NAV2 & MoveIt2", icon: "compass", count: 7 },
  { id: "slam", name: "SLAM", icon: "map-pin", count: 5 },
  { id: "computer-vision", name: "Computer Vision", icon: "eye", count: 8 },
  { id: "microros", name: "MicroROS", icon: "zap", count: 2 },
  { id: "sensor-fusion", name: "Sensor Fusion", icon: "radio", count: 1 },
  { id: "ml-robotics", name: "ML for Robotics", icon: "terminal", count: 6 },
  { id: "docker", name: "Docker", icon: "box", count: 2 },
  { id: "cad", name: "CAD & Modeling", icon: "box-3d", count: 4 }
];

const ROADMAP_STEPS = [
  {
    step: 1,
    phase: "phase-1",
    title: "Foundations",
    subtitle: "Python & CAD Modeling",
    description: "Build programming muscle memory and 3D spatial thinking before diving into robotic software.",
    categoryIds: ["computer-vision", "cad"],
    tags: ["python", "cad", "solidworks"],
    color: "#38bdf8"
  },
  {
    step: 2,
    phase: "phase-2",
    title: "ROS2 Humble Core",
    subtitle: "Architecture, TF2 & URDF",
    description: "Master nodes, topics, services, launch scripts, and robot kinematic trees in ROS2 Humble.",
    categoryIds: ["ros2"],
    tags: ["ros2", "humble", "tf2", "urdf"],
    color: "#818cf8"
  },
  {
    step: 3,
    phase: "phase-3",
    title: "Controls & Embedded",
    subtitle: "Kalman, ros2_control & MicroROS",
    description: "Bridge high-level algorithms to hardware actuators, microcontrollers, and state estimation.",
    categoryIds: ["control-systems", "microros", "docker"],
    tags: ["control", "kalman", "microros", "docker"],
    color: "#c084fc"
  },
  {
    step: 4,
    phase: "phase-4",
    title: "Autonomy & SLAM",
    subtitle: "NAV2, MoveIt2 & Mapping",
    description: "Implement simultaneous localization and mapping, obstacle avoidance, and robotic arm path planning.",
    categoryIds: ["nav2-moveit2", "slam"],
    tags: ["nav2", "moveit2", "slam", "cartographer"],
    color: "#34d399"
  },
  {
    step: 5,
    phase: "phase-5",
    title: "Perception & AI",
    subtitle: "YOLO, Sensor Fusion & RL",
    description: "Deploy deep neural vision models, multivariant sensor filtering, and reinforcement learning.",
    categoryIds: ["computer-vision", "sensor-fusion", "ml-robotics"],
    tags: ["yolo", "opencv", "sensor-fusion", "reinforcement-learning"],
    color: "#f472b6"
  }
];

const RESOURCES = [
  // --- ROS2 ---
  {
    id: "ros2-awesome-repo",
    title: "Generalised ROS2 Repository (Awesome-ROS2)",
    category: "ros2",
    categoryName: "ROS2",
    type: "github",
    typeName: "GitHub Repo",
    url: "https://github.com/fkromer/awesome-ros2?tab=readme-ov-file",
    author: "fkromer",
    description: "An extensive curated list of awesome Robot Operating System 2 (ROS 2) libraries, tools, and learning materials.",
    proTip: "A goldmine reference repository to bookmark for finding packages, drivers, and best architectural patterns.",
    tags: ["ROS2", "Curated List", "Architecture", "Open Source"],
    phase: "phase-2",
    stars: "Featured"
  },
  {
    id: "ros2-book",
    title: "ROS2 Comprehensive Guide & Book",
    category: "ros2",
    categoryName: "ROS2",
    type: "book",
    typeName: "Book / GitBook",
    url: "https://github.com/fmrico/book_ros2",
    author: "fmrico",
    description: "Practical guide to programming robotics applications in ROS2, featuring structured chapters on nodes, lifecycle, and topics.",
    proTip: "Read chapters sequentially alongside hands-on terminal practice to master the underlying client library mechanics.",
    tags: ["ROS2", "Book", "C++", "Python", "Robotics"],
    phase: "phase-2"
  },
  {
    id: "ros2-tutorials-playlist",
    title: "ROS 2 Tutorials Video Playlist",
    category: "ros2",
    categoryName: "ROS2",
    type: "playlist",
    typeName: "YouTube Playlist",
    url: "https://youtube.com/playlist?list=PLLSegLrePWgJudpPUof4-nVFHGkB62Izy&si=_N88x58oVMCJmm1T",
    author: "Community",
    description: "Step-by-step video tutorials introducing core ROS2 fundamentals, environment configuration, workspace setup, and publisher/subscriber models.",
    proTip: "Great for building initial visual intuition on how nodes interact across the DDS middleware.",
    tags: ["ROS2", "Beginner", "Tutorial", "Workspace"],
    phase: "phase-2"
  },
  {
    id: "ros2-humble-detailed-playlist",
    title: "ROS2 Humble Detailed In-Depth Playlist",
    category: "ros2",
    categoryName: "ROS2",
    type: "playlist",
    typeName: "YouTube Playlist",
    url: "https://youtube.com/playlist?list=PLSK7NtBWwmpTS_YVfjeN3ZzIxItI1P_Sr&si=JA6_GEm3rG7fJfQd",
    author: "Articulated Robotics",
    description: "Comprehensive walkthrough of ROS2 Humble—the industry standard LTS release—covering simulation, robot descriptions, and transforms.",
    proTip: "Don't go through everything! Focus specifically on tf2 and urdf modules first to save hours of time.",
    tags: ["ROS2 Humble", "TF2", "URDF", "LTS Standard"],
    phase: "phase-2",
    recommended: true
  },
  {
    id: "ros2-oneshot-1",
    title: "ROS 2 One-Shot Crash Course (Video 1)",
    category: "ros2",
    categoryName: "ROS2",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/Gg25GfA456o?si=XQF0O3Wxzi6Kpo9v",
    author: "Tinkerers Lab Recommended",
    description: "High-density, fast-paced single session explaining ROS2 concepts in one continuous video to get you building rapidly.",
    proTip: "Watch this before starting multi-hour playlists to get the big-picture context in a single afternoon.",
    tags: ["ROS2", "Crash Course", "Fast Track"],
    phase: "phase-2"
  },
  {
    id: "ros2-oneshot-2",
    title: "ROS 2 One-Shot Deep Dive (Video 2)",
    category: "ros2",
    categoryName: "ROS2",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/HJAE5Pk8Nyw?si=XaAPTn4-ApLQIdSG",
    author: "Tinkerers Lab Recommended",
    description: "Companion one-shot lecture covering essential ROS2 mechanics, command line utilities, and package builds with colcon.",
    proTip: "Ideal refresher when you need to quickly recall colcon build flags and package manifest configs.",
    tags: ["ROS2", "Colcon", "CLI", "Crash Course"],
    phase: "phase-2"
  },
  {
    id: "ros2-launch-files",
    title: "ROS2 Launch File Creation & Debugging",
    category: "ros2",
    categoryName: "ROS2",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/ViyseWFVn6M?si=6i5U50Dp21UL1hUg",
    author: "Robotics Dev",
    description: "Learn how to write dynamic Python-based ROS2 launch files, pass runtime arguments, remap topics, and debug launch failures.",
    proTip: "Launch files are the backbone of any production robotics stack; practice parameter passing early.",
    tags: ["Launch Files", "Python", "Debugging", "Architecture"],
    phase: "phase-2"
  },
  {
    id: "ros2-rviz2-tutorial",
    title: "Rviz2 3D Robot Visualization Tutorial",
    category: "ros2",
    categoryName: "ROS2",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/qWoGkPDg4N8?si=r_rg07i31iMtJQfd",
    author: "Robotics Dev",
    description: "Practical guide to visualizing laser scans, point clouds, robot coordinate frames (tf), and camera streams inside Rviz2.",
    proTip: "Keep Rviz2 open whenever you test node transforms—visual inspection catches 90% of tf2 bugs.",
    tags: ["Rviz2", "Visualization", "TF", "Point Clouds"],
    phase: "phase-2"
  },

  // --- Control Systems ---
  {
    id: "control-kalman-filter",
    title: "Kalman Filter Theory & Mathematical Foundation",
    category: "control-systems",
    categoryName: "Control Systems",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/sVnXG-xUhzU?si=xewYnNJTDIeW-uOo",
    author: "Specialist Lecture",
    description: "Clear and intuitive breakdown of Kalman Filters, covariance matrices, state estimation, and sensor noise suppression.",
    proTip: "Focus on understanding the Prediction vs Update step equations; this underpins robot state estimation.",
    tags: ["Kalman Filter", "State Estimation", "Mathematics", "Probability"],
    phase: "phase-3",
    recommended: true
  },
  {
    id: "control-ros2-control-visual",
    title: "ros2_control Framework: Visual Representation",
    category: "control-systems",
    categoryName: "Control Systems",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/4QKsDf1c4hc?si=IeXbKi8-KEt0KlC-",
    author: "Robotics Architecture",
    description: "Visual architectural walkthrough of ros2_control—controller managers, hardware interfaces, and command/state interfaces.",
    proTip: "Grasping how the Resource Manager communicates with hardware plugins is key to building custom robots.",
    tags: ["ros2_control", "Hardware Interface", "Actuators", "Controllers"],
    phase: "phase-3"
  },
  {
    id: "control-applied-systems-course",
    title: "Applied Control Systems for Engineers (PID, MPC)",
    category: "control-systems",
    categoryName: "Control Systems",
    type: "course",
    typeName: "Udemy Course",
    url: "https://www.udemy.com/course/applied-systems-control-for-engineers-modelling-pid-mpc/",
    author: "Udemy Instructor",
    description: "Comprehensive hands-on course teaching dynamic modeling, PID tuning, state-space control, and Model Predictive Control (MPC).",
    proTip: "Great practical exercise for moving beyond naive P/PID controllers to modern predictive optimal control.",
    tags: ["PID", "MPC", "Control Theory", "Engineering"],
    phase: "phase-3"
  },

  // --- NAV2 & MoveIt2 ---
  {
    id: "nav2-interpolated-1",
    title: "NAV2 Interpolated Guide (Part 1)",
    category: "nav2-moveit2",
    categoryName: "NAV2 and MoveIt2",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/bYTawHgVoRQ?si=4V3s2oacVTsfi6WP",
    author: "Navigation Specialist",
    description: "Explores NAV2 interpolated trajectory generation and path smoothing for mobile robots.",
    proTip: "Demonstrated on Foxy, but cleanly replicable in ROS2 Humble with minor parameter name updates.",
    tags: ["NAV2", "Path Planning", "Trajectories", "Mobile Robots"],
    phase: "phase-4"
  },
  {
    id: "nav2-interpolated-2",
    title: "NAV2 Interpolated Guide (Part 2)",
    category: "nav2-moveit2",
    categoryName: "NAV2 and MoveIt2",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/q4l_-n4BrKA?si=jQprEXufnLsR9pG7",
    author: "Navigation Specialist",
    description: "Continuation of NAV2 trajectory interpolation covering dynamic costmaps, obstacle inflation, and recovery behaviors.",
    proTip: "Notice how costmap layers interact with local planners like DWB or TEB.",
    tags: ["NAV2", "Costmaps", "Local Planner", "Recovery"],
    phase: "phase-4"
  },
  {
    id: "nav2-full-playlist",
    title: "NAV2 Complete Video Playlist",
    category: "nav2-moveit2",
    categoryName: "NAV2 and MoveIt2",
    type: "playlist",
    typeName: "YouTube Playlist",
    url: "https://youtube.com/playlist?list=PLgG0XDQqJcknP8fhdAXxYv6AYnfqjP6WU&si=f6HEBTX65UH62DsN",
    author: "Autonomous Robotics Hub",
    description: "End-to-end video tutorial series on configuring NAV2 stack for custom differential drive and ackermann robots.",
    proTip: "Follow along step by step to tune global/local planners and behavior trees without guessing parameters.",
    tags: ["NAV2", "Behavior Trees", "Autonomous Navigation", "Playlist"],
    phase: "phase-4",
    recommended: true
  },
  {
    id: "nav2-project-layout",
    title: "NAV2 Project with Basic Layout (Foxy/Humble)",
    category: "nav2-moveit2",
    categoryName: "NAV2 and MoveIt2",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/EOBbxBBDLxU?si=6Faou_hdQELxVfKH",
    author: "Robotics Builder",
    description: "Hands-on project showing how to structure navigation packages, configuration yaml files, and launch pipelines.",
    proTip: "Provides a clean repository boilerplate that you can adapt directly for your own robot chassis.",
    tags: ["Project", "NAV2", "Config YAML", "Architecture"],
    phase: "phase-4"
  },
  {
    id: "nav2-project-part-2",
    title: "NAV2 Autonomous Project (Part 2)",
    category: "nav2-moveit2",
    categoryName: "NAV2 and MoveIt2",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/V0kmKkO7tVo?si=irgDDWAQMoAQIYMx",
    author: "Robotics Builder",
    description: "Deep dive into real-time waypoint following, dynamic obstacle avoidance, and goal pose dispatching via ROS2 action clients.",
    proTip: "Learn how the Action Server protocol works under the hood for long-running navigation goals.",
    tags: ["NAV2", "Action Client", "Waypoints", "Obstacle Avoidance"],
    phase: "phase-4"
  },
  {
    id: "nav2-moveit2-manipulator",
    title: "NAV2 & MoveIt2 Integrated Project (Mobile Manipulator)",
    category: "nav2-moveit2",
    categoryName: "NAV2 and MoveIt2",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/EosEikbZhiM?si=rAFiwoCW53hVBqe8",
    author: "Advanced Robotics",
    description: "Integration of mobile base navigation (NAV2) with robotic arm trajectory planning (MoveIt2) for pick-and-place tasks.",
    proTip: "One of the best projects to demonstrate full-stack robotics skills on your portfolio or resume.",
    tags: ["MoveIt2", "NAV2", "Manipulator", "Kinematics", "Cap-Stone"],
    phase: "phase-4",
    recommended: true
  },
  {
    id: "nav2-mapping",
    title: "NAV2 2D/3D Grid Mapping Implementation",
    category: "nav2-moveit2",
    categoryName: "NAV2 and MoveIt2",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/rZOxPGCn4QM?si=3m7k3IUkydBIZlDk",
    author: "Robotics Specialist",
    description: "Learn how occupancy grid maps are constructed, updated, and saved using Nav2 Map Server and laser scans.",
    proTip: "Make sure to set map resolution and update frequencies appropriate for your sensor range.",
    tags: ["Mapping", "Occupancy Grid", "Map Server", "LiDAR"],
    phase: "phase-4"
  },

  // --- SLAM ---
  {
    id: "slam-cartographer",
    title: "Google Cartographer ROS2",
    category: "slam",
    categoryName: "SLAM",
    type: "github",
    typeName: "GitHub Repo",
    url: "https://github.com/ros2/cartographer",
    author: "Google / ROS2",
    description: "Real-time simultaneous localization and mapping (SLAM) in 2D and 3D across multiple platforms and sensor configurations.",
    proTip: "Excellent for multi-sensor setups and large indoor environments with loop closure requirements.",
    tags: ["Cartographer", "Google", "2D/3D SLAM", "Loop Closure"],
    phase: "phase-4"
  },
  {
    id: "slam-toolbox",
    title: "SLAM Toolbox (ROS2 Standard)",
    category: "slam",
    categoryName: "SLAM",
    type: "github",
    typeName: "GitHub Repo",
    url: "https://github.com/SteveMacenski/slam_toolbox",
    author: "Steve Macenski",
    description: "The official standard SLAM package for ROS2, featuring lifetime mapping, synchronous/asynchronous modes, and serialization.",
    proTip: "Currently the default and recommended SLAM algorithm for ROS2 Humble navigation pipelines.",
    tags: ["SLAM Toolbox", "ROS2 Standard", "Lifelong Mapping", "Lidar"],
    phase: "phase-4",
    recommended: true
  },
  {
    id: "slam-gmapping",
    title: "SLAM GMapping Port for ROS2",
    category: "slam",
    categoryName: "SLAM",
    type: "github",
    typeName: "GitHub Repo",
    url: "https://github.com/Project-MANAS/slam_gmapping",
    author: "Project MANAS",
    description: "ROS2 port of the classic Rao-Blackwellized particle filter SLAM algorithm for 2D laser range finders.",
    proTip: "Great for educational understanding of particle filter based mapping in simpler structured indoor spaces.",
    tags: ["GMapping", "Particle Filter", "Laser", "Project MANAS"],
    phase: "phase-4"
  },
  {
    id: "slam-course-autonomous-driving",
    title: "Robotics with ROS: Autonomous Driving & SLAM Course",
    category: "slam",
    categoryName: "SLAM",
    type: "course",
    typeName: "Udemy Course",
    url: "https://www.udemy.com/course/robotics-with-ros-autonomous-driving-and-path-planning-slam/?couponCode=CM251217G1",
    author: "Udemy Course",
    description: "Structured course on building autonomous driving vehicles, path planning algorithms, and SLAM map creation.",
    proTip: "Covers the full pipeline from simulated sensors to path execution.",
    tags: ["Autonomous Driving", "SLAM", "Path Planning", "Simulation"],
    phase: "phase-4"
  },
  {
    id: "slam-course-ros-navigation",
    title: "ROS Navigation & Mobile Robotics",
    category: "slam",
    categoryName: "SLAM",
    type: "course",
    typeName: "Udemy Course",
    url: "https://www.udemy.com/course/ros-navigation/?couponCode=CM251217G1",
    author: "Udemy Course",
    description: "In-depth course on localization (AMCL), global/local path planners, and differential drive kinematics.",
    proTip: "Solid choice if you prefer structured video lessons with quiz checkpoints and assignments.",
    tags: ["AMCL", "Localization", "Navigation", "Differential Drive"],
    phase: "phase-4"
  },

  // --- Computer Vision ---
  {
    id: "cv-python-oneshot",
    title: "Python One Shot Rapid Tutorial",
    category: "computer-vision",
    categoryName: "Computer Vision",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/vLqTf2b6GZw?si=v6ktqDFBv135Eo0z",
    author: "Programming Channel",
    description: "Speedrun covering Python syntax, data structures, functions, and OOP to prepare for scripting robotics nodes.",
    proTip: "Any 1-2 hr one-shot is enough to get syntax ideas. Don't get stuck in tutorial loops; jump straight into code!",
    tags: ["Python", "Beginner", "Crash Course", "Syntax"],
    phase: "phase-1"
  },
  {
    id: "cv-opencv-playlist",
    title: "OpenCV Full Mastery Playlist",
    category: "computer-vision",
    categoryName: "Computer Vision",
    type: "playlist",
    typeName: "YouTube Playlist",
    url: "https://youtube.com/playlist?list=PLGs0VKk2DiYyXlbJVaE8y1qr24YldYNDm&si=qdW0cyqXadH0A_ET",
    author: "Paul McWhorter / Specialist",
    description: "Comprehensive hands-on OpenCV series covering image transformations, color thresholds, edge detection, and contours.",
    proTip: "Start directly from video 6 if your OpenCV environment is already installed. Watch at 2x speed for maximum efficiency!",
    tags: ["OpenCV", "Image Processing", "Contours", "Thresholding"],
    phase: "phase-5",
    recommended: true
  },
  {
    id: "cv-opencv-alternative",
    title: "Alternative Comprehensive OpenCV Tutorial",
    category: "computer-vision",
    categoryName: "Computer Vision",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/5Vo4usE4-HA?si=XaGiShUgossLGWzs",
    author: "Computer Vision Specialist",
    description: "Single-video comprehensive guide to OpenCV concepts, covering morphology, blurring, Hough transforms, and video capture.",
    proTip: "A great alternative single-video format if you prefer watching one continuous video instead of a playlist.",
    tags: ["OpenCV", "Computer Vision", "Video Guide"],
    phase: "phase-5"
  },
  {
    id: "cv-project-ideas",
    title: "Computer Vision Real-World Project Ideas",
    category: "computer-vision",
    categoryName: "Computer Vision",
    type: "playlist",
    typeName: "YouTube Playlist",
    url: "https://youtube.com/playlist?list=PLMoSUbG1Q_r8jFS04rot-3NzidnV54Z2q&si=Gcxp2Z0x3F1OypQt",
    author: "Murtaza's Workshop",
    description: "Build practical vision projects: pose estimation, hand gesture tracking, optical flow, and object measurement.",
    proTip: "Try to implement the projects yourself without looking at the solution code first to truly learn.",
    tags: ["Projects", "Hands-On", "Gesture Tracking", "OpenCV"],
    phase: "phase-5"
  },
  {
    id: "cv-cnns-playlist",
    title: "Convolutional Neural Networks (CNNs) Playlist",
    category: "computer-vision",
    categoryName: "Computer Vision",
    type: "playlist",
    typeName: "YouTube Playlist",
    url: "https://youtu.be/2dH_qjc9mFg?si=xeceVB37z_mfDhrq",
    author: "Deep Learning Series",
    description: "Covers convolution kernels, pooling layers, feature maps, and modern architectures (ResNet, VGG).",
    proTip: "Watch videos 40 to 50 for the meat of CNNs. Understanding backpropagation mathematically is optional for practical robotics!",
    tags: ["CNN", "Deep Learning", "Kernels", "Feature Maps"],
    phase: "phase-5"
  },
  {
    id: "cv-neural-networks-concept",
    title: "Neural Networks Intuitive Visual Concept",
    category: "computer-vision",
    categoryName: "Computer Vision",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/aircAruvnKk?si=49MO5-nBkOSlRT3J",
    author: "3Blue1Brown style intuition",
    description: "Visually stunning conceptual explanation of weights, biases, activations, and gradient descent.",
    proTip: "Essential conceptual viewing if you've ever found neural network math intimidating.",
    tags: ["Neural Networks", "Deep Learning", "Intuition"],
    phase: "phase-5"
  },
  {
    id: "cv-yolo-1",
    title: "YOLO Object Detection & Tracking (Video 1)",
    category: "computer-vision",
    categoryName: "Computer Vision",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/svn9-xV7wjk?si=dVQAaExX0Bn8FzdY",
    author: "Vision AI",
    description: "Training and running real-time YOLO object detection models for edge robotics and camera streams.",
    proTip: "Use ONNX or TensorRT export when deploying YOLO to resource-constrained robot computers like Jetson Nano.",
    tags: ["YOLO", "Object Detection", "Edge AI", "Real-Time"],
    phase: "phase-5"
  },
  {
    id: "cv-yolo-2",
    title: "YOLO Real-Time Detection & Multi-Object Tracking (Video 2)",
    category: "computer-vision",
    categoryName: "Computer Vision",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/r0RspiLG260?si=pf6X00ziuFXNgmdV",
    author: "Vision AI",
    description: "Combining YOLO object bounding boxes with SORT/DeepSORT for persistent multi-object tracking in video streams.",
    proTip: "Crucial for robotics tasks where you need to track dynamic moving obstacles across consecutive video frames.",
    tags: ["YOLO", "DeepSORT", "Object Tracking", "Robotics Vision"],
    phase: "phase-5"
  },
  {
    id: "cv-ocr-tutorial",
    title: "Optical Character Recognition (OCR) Tutorial",
    category: "computer-vision",
    categoryName: "Computer Vision",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/HHHkh9IOqhI?si=ynfXlWlwgICtsh76",
    author: "Computer Vision Dev",
    description: "Extracting text labels, barcodes, and signs from camera images using Tesseract and pytesseract.",
    proTip: "Or use any tutorial to setup pytesseract—ensure you apply bilateral filtering to improve OCR accuracy on noisy camera feeds.",
    tags: ["OCR", "Tesseract", "pytesseract", "Text Recognition"],
    phase: "phase-5"
  },

  // --- MicroROS ---
  {
    id: "microros-arduino",
    title: "micro-ROS for Arduino Ecosystem",
    category: "microros",
    categoryName: "MicroROS",
    type: "github",
    typeName: "GitHub Repo",
    url: "https://github.com/micro-ROS/micro_ros_arduino",
    author: "micro-ROS Project",
    description: "Brings ROS2 directly to microcontrollers (ESP32, Teensy, SAMD) with native publisher/subscriber support over serial or Wi-Fi.",
    proTip: "The most practical bridge for reading encoders, IMUs, and controlling motor PWM pins directly inside ROS2 topics.",
    tags: ["micro-ROS", "Arduino", "ESP32", "Microcontrollers", "Embedded"],
    phase: "phase-3",
    recommended: true
  },
  {
    id: "microros-zephyr",
    title: "micro-ROS for Zephyr RTOS Module",
    category: "microros",
    categoryName: "MicroROS",
    type: "github",
    typeName: "GitHub Repo",
    url: "https://github.com/micro-ROS/micro_ros_zephyr_module",
    author: "micro-ROS Project",
    description: "Integrate micro-ROS with the industry-grade Zephyr real-time operating system (RTOS) for deterministic embedded execution.",
    proTip: "Use this when your robotics project requires hard real-time guarantees and multi-threading on Cortex-M processors.",
    tags: ["Zephyr RTOS", "micro-ROS", "Embedded", "Real-Time"],
    phase: "phase-3"
  },

  // --- Sensor Fusion ---
  {
    id: "sensor-fusion-course",
    title: "Self Driving & ROS 2: Odometry & Sensor Fusion",
    category: "sensor-fusion",
    categoryName: "Sensor Fusion",
    type: "course",
    typeName: "Udemy Course",
    url: "https://www.udemy.com/course/self-driving-and-ros-2-learn-by-doing-odometry-control/?couponCode=CM251217G1",
    author: "Learn by Doing",
    description: "Comprehensive hands-on course covering robot odometry, IMU sensor fusion using robot_localization EKF, and differential drive control.",
    proTip: "Exceptionally good for mastering odometry calibration and configuring the robot_localization Extended Kalman Filter.",
    tags: ["Sensor Fusion", "EKF", "Odometry", "IMU", "robot_localization"],
    phase: "phase-5",
    recommended: true
  },

  // --- Machine Learning for Robotics ---
  {
    id: "ml-robotics-playlist",
    title: "Machine Learning in Robotics Complete Course",
    category: "ml-robotics",
    categoryName: "ML for Robotics",
    type: "playlist",
    typeName: "YouTube Playlist",
    url: "https://youtube.com/playlist?list=PLlqdnFs9xNwrAV19_HN0itHVKy09uR7dV&si=5DDwMhJTKiyTSPu5",
    author: "Academic Lecturer",
    description: "Comprehensive playlist covering regression, clustering, neural policies, and reinforcement learning tailored for roboticists.",
    proTip: "Don't try to binge the entire course at once—learn topics modularly as needed for your specific robotics sub-problem.",
    tags: ["Machine Learning", "Robotics", "Policies", "Lectures"],
    phase: "phase-5"
  },
  {
    id: "ml-rl-video-1",
    title: "Reinforcement Learning Core Concepts (Video 1)",
    category: "ml-robotics",
    categoryName: "ML for Robotics",
    type: "video",
    typeName: "YouTube Video",
    url: "https://youtu.be/Mut_u40Sqz4?si=4oBwWJ-U6DIsodfU",
    author: "AI Educator",
    description: "Introduction to Markov Decision Processes (MDPs), policy iteration, value iteration, and Q-learning for agents.",
    proTip: "Grasp how reward function shaping dictates the physical stability of simulated walking robots.",
    tags: ["Reinforcement Learning", "MDP", "Q-Learning"],
    phase: "phase-5"
  },
  {
    id: "ml-rl-video-2",
    title: "Deep Reinforcement Learning Live Masterclass (Video 2)",
    category: "ml-robotics",
    categoryName: "ML for Robotics",
    type: "video",
    typeName: "YouTube Video",
    url: "https://www.youtube.com/live/XDw03aM6FeQ?si=3XWO0aJg9_VZ2MZO",
    author: "Live AI Masterclass",
    description: "Interactive session diving into policy gradient methods (PPO, SAC) and their application in simulation environments like Isaac Gym and MuJoCo.",
    proTip: "PPO (Proximal Policy Optimization) and SAC (Soft Actor-Critic) are the premier algorithms for continuous robotic joint control.",
    tags: ["Deep RL", "PPO", "SAC", "Continuous Control"],
    phase: "phase-5"
  },
  {
    id: "ml-sutton-barto-book",
    title: "Reinforcement Learning: An Introduction (Sutton & Barto)",
    category: "ml-robotics",
    categoryName: "ML for Robotics",
    type: "book",
    typeName: "Classic Textbook (PDF)",
    url: "https://web.stanford.edu/class/psych209/Readings/SuttonBartoIPRLBook2ndEd.pdf",
    author: "Richard S. Sutton & Andrew G. Barto",
    description: "The universally recognized 'Bible' of Reinforcement Learning. Essential theoretical reference from foundational tabular methods to function approximation.",
    proTip: "Read Chapters 3, 4, and 6 for a rock-solid understanding of Dynamic Programming and Temporal-Difference learning.",
    tags: ["Sutton & Barto", "RL Bible", "Textbook", "Stanford"],
    phase: "phase-5",
    recommended: true
  },
  {
    id: "ml-arxiv-paper-1",
    title: "Research Paper: Deep Reinforcement Learning for Robotics",
    category: "ml-robotics",
    categoryName: "ML for Robotics",
    type: "paper",
    typeName: "ArXiv Research Paper",
    url: "https://arxiv.org/abs/2210.07397",
    author: "ArXiv Researchers",
    description: "Cutting-edge survey paper analyzing sim-to-real transfer, domain randomization, and real-world deployment challenges of robotic RL policies.",
    proTip: "Check the Sim-to-Real transfer methodology section; domain randomization is vital when transferring policies to physical robots.",
    tags: ["ArXiv", "Research Paper", "Sim-to-Real", "Domain Randomization"],
    phase: "phase-5"
  },
  {
    id: "ml-arxiv-paper-2",
    title: "Research Paper: End-to-End Robotic Learning Foundations",
    category: "ml-robotics",
    categoryName: "ML for Robotics",
    type: "paper",
    typeName: "ArXiv Research Paper",
    url: "https://arxiv.org/abs/1811.06711",
    author: "ArXiv Researchers",
    description: "Foundational research paper exploring end-to-end motor control policies learned directly from visual and proprioceptive inputs.",
    proTip: "Compare end-to-end policy learning against modular classical pipelines (perception -> planning -> control) to understand trade-offs.",
    tags: ["ArXiv", "Research Paper", "End-to-End", "Motor Control"],
    phase: "phase-5"
  },
  {
    id: "ml-google-crash-course",
    title: "Google Machine Learning Crash Course (Neural Networks)",
    category: "ml-robotics",
    categoryName: "ML for Robotics",
    type: "course",
    typeName: "Google Documentation / Course",
    url: "https://developers.google.com/machine-learning/crash-course/neural-networks",
    author: "Google Developers",
    description: "Interactive visual modules from Google engineers explaining nonlinear transformations, loss functions, learning rates, and regularization.",
    proTip: "Interactive browser widgets allow you to manipulate hyper-parameters in real time without configuring local GPUs.",
    tags: ["Google ML", "Neural Networks", "Free Course", "Interactive"],
    phase: "phase-5"
  },

  // --- Docker ---
  {
    id: "docker-ros2-openslice",
    title: "Docker ROS2 OpenSplice / Cyclone DDS Container",
    category: "docker",
    categoryName: "Docker",
    type: "github",
    typeName: "GitHub Repo",
    url: "https://github.com/Adlink-ROS/docker-ros2-ospl-ce",
    author: "Adlink-ROS",
    description: "Production-ready Dockerfiles configured for ROS2 DDS communication, zero-configuration networking, and containerized deployment.",
    proTip: "Eliminates 'works on my machine' problems across different Linux distributions and team workstations.",
    tags: ["Docker", "DDS", "Containerization", "DevOps"],
    phase: "phase-3"
  },
  {
    id: "docker-microros",
    title: "micro-ROS Official Docker Environment",
    category: "docker",
    categoryName: "Docker",
    type: "github",
    typeName: "GitHub Repo",
    url: "https://github.com/micro-ROS/docker",
    author: "micro-ROS Community",
    description: "Ready-to-use Docker container containing the micro-ROS Agent, toolchains, and firmware compilation dependencies.",
    proTip: "Use the pre-built Agent Docker image to run the micro-ROS Agent on your host PC with a single docker run command!",
    tags: ["micro-ROS Agent", "Docker", "Embedded", "Quickstart"],
    phase: "phase-3",
    recommended: true
  },

  // --- CAD & Modeling ---
  {
    id: "cad-basics-playlist-1",
    title: "CAD Modeling Fundamentals (Playlist 1)",
    category: "cad",
    categoryName: "CAD",
    type: "playlist",
    typeName: "YouTube Playlist",
    url: "https://youtube.com/playlist?list=PLRhna5_X7uWsdDWnvtuIzPlK8yZKSbWJR&si=B4a_mH8ee0hNOwRJ",
    author: "CAD Academy",
    description: "Foundational CAD concepts: sketches, geometric constraints, extrusions, revolves, and assembly mates.",
    proTip: "Not recommended to watch this completely as a tutorial! Scan key concepts and jump straight into modeling real parts.",
    tags: ["CAD", "Parametric Modeling", "Sketches", "Extrude"],
    phase: "phase-1"
  },
  {
    id: "cad-basics-playlist-2",
    title: "CAD Modeling Secondary Series (Playlist 2)",
    category: "cad",
    categoryName: "CAD",
    type: "playlist",
    typeName: "YouTube Playlist",
    url: "https://youtube.com/playlist?list=PLRhna5_X7uWt5SQUMmNzV0aBMiggB0ROw&si=FOt2Dh-C-hL8g9yr",
    author: "CAD Academy",
    description: "Intermediate CAD assembly techniques, multi-body parts, sheet metal design, and technical drawing generation.",
    proTip: "Learn how to export STL/STEP files with the correct origin and coordinate system for ROS URDF meshes.",
    tags: ["CAD", "Assemblies", "Drawings", "Export"],
    phase: "phase-1"
  },
  {
    id: "cad-cam-channel",
    title: "CAD CAM Tutorial Channel (By Mahtab Alam)",
    category: "cad",
    categoryName: "CAD",
    type: "youtube",
    typeName: "YouTube Channel",
    url: "https://www.youtube.com/@CADCAMTUTORIALBYMAHTABALAM",
    author: "Mahtab Alam",
    description: "Renowned YouTube channel featuring hundreds of step-by-step CAD mechanical modeling exercises for real mechanical assemblies.",
    proTip: "The gold standard channel for learning SolidWorks and mechanical modeling through realistic practice components.",
    tags: ["SolidWorks", "CAD/CAM", "Mechanical", "Mahtab Alam"],
    phase: "phase-1",
    recommended: true
  },
  {
    id: "cad-recommended-playlist",
    title: "Recommended CAD Parts Practical Exercises",
    category: "cad",
    categoryName: "CAD",
    type: "playlist",
    typeName: "YouTube Playlist",
    url: "https://youtube.com/playlist?list=PLRhna5_X7uWuIMRdqUG9gqKwBKI1Hr__X&si=bprle54qp9ZuLOfQ",
    author: "CAD CAM Tutorial",
    description: "Curated collection of practical component designs—gears, brackets, housings, robot chassis, and mechanical links.",
    proTip: "Start CAD by doing the parts side-by-side from the initial 2D sketch! Hands-on practice beats passive video watching every time.",
    tags: ["Parts Modeling", "Robot Chassis", "Gears", "Practical Exercises"],
    phase: "phase-1",
    recommended: true
  }
];
